# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_recv', models.IntegerField()),
                ('bytes_sent', models.IntegerField()),
                ('packets_recv', models.IntegerField()),
                ('packets_sent', models.IntegerField()),
                ('usagelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UsageLog')),
            ],
        ),
    ]
