# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_networkusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
