# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161109_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
