# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_server_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuplog',
            name='log',
        ),
        migrations.RemoveField(
            model_name='backuplog',
            name='success',
        ),
        migrations.AddField(
            model_name='backuplog',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
