# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161113_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backuptarget',
            old_name='path',
            new_name='path_template',
        ),
        migrations.AddField(
            model_name='backuplog',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
