# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161113_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuptarget',
            name='name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
