# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backuptarget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusage',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='diskusage',
            name='used',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='networkusage',
            name='bytes_recv',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='networkusage',
            name='bytes_sent',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='networkusage',
            name='packets_recv',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='networkusage',
            name='packets_sent',
            field=models.BigIntegerField(),
        ),
    ]
